In [1]:
import torch

In [4]:
if torch.cuda.is_available():
    print("GPU is available")
    print(torch.cuda.get_device_name()[0])
else:
    print("GPU is not available")

GPU is not available


In [6]:
t1 = torch.empty(2,3)
print(t1)

tensor([[1.1458e-13, 1.2486e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [7]:
t2 = torch.zeros(2,3)
t2

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
t3 = torch.rand(2,3)
t3

tensor([[0.8224, 0.9476, 0.6407],
        [0.7041, 0.4279, 0.2501]])

In [19]:
torch.manual_seed(42)
t4 = torch.rand(2,3)
print(t4)
t4 = torch.rand(2,3)
print(t4)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])


In [17]:
t4 = torch.rand(2,3)
t4

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [23]:
t5 = torch.tensor([[1,2,3], [4,5,6]], dtype = torch.float32)
t5.dtype

torch.float32

In [24]:
torch.arange(0, 100, 5)

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [25]:
torch.linspace(0, 100, 5)

tensor([  0.,  25.,  50.,  75., 100.])

In [26]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [28]:
torch.full((3,3), 6)

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [29]:
t5.shape

torch.Size([2, 3])

In [30]:
torch.empty_like(t1)

tensor([[1.1459e-13, 1.2486e-42, 6.4065e-01],
        [7.0409e-01, 4.2793e-01, 2.5006e-01]])

In [32]:
torch.zeros_like(t5)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [33]:
t3.dtype

torch.float32

In [34]:
t1.to(torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [35]:
torch.rand_like(t4)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [45]:
x = torch.rand(2,2)
x

tensor([[0.2969, 0.8317],
        [0.1053, 0.2695]])

In [ ]:
# x + 2
# x - 2
# x * 2
# x / 2
# x % 2
# x ** 2
# x // 2

tensor([[0., 0.],
        [0., 0.]])

In [51]:
x = torch.rand(2,2)
y = torch.rand(2,2)
x,y

(tensor([[0.3588, 0.1994],
         [0.5472, 0.0062]]),
 tensor([[0.9516, 0.0753],
         [0.8860, 0.5832]]))

In [ ]:
# x + y
# x - y
# x * y
# x / y
# x % y
# x ** y
# x // y

tensor([[0., 2.],
        [0., 0.]])

In [ ]:
x = torch.tensor([1, -2, 3, -4])
# torch.abs(x)
# torch.neg(x)
# torch.round(x)
# torch.ceil(x)
# torch.floor(x)


tensor([-1,  2, -3,  4])

In [64]:
y = torch.tensor([1.9, 2.3, 3.7, 4.3])
torch.clamp(y,min = 2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [ ]:
x = torch.randint(size = (2,3), low = 0, high = 10)
torch.sum(x)
torch.sum(x, dim = 0)
torch.sum(x, dim = 1)

tensor([10, 16])

In [71]:
x = torch.rand(size = (2,3))

In [ ]:
# torch.mean(x)
# torch.mean(x, dim = 0)
# torch.mean(x, dim = 1)

tensor(0.5879)

In [75]:
torch.median(x)

tensor(0.6440)

In [77]:
torch.max(x), torch.min(x), torch.argmax(x), torch.argmin(x)

(tensor(0.9103), tensor(0.1165), tensor(1), tensor(0))

In [78]:
x = torch.rand(size = (2,3))
y = torch.rand(size = (3,2))
torch.matmul(x,y)

tensor([[0.8219, 0.4895],
        [0.7682, 0.2622]])

In [84]:
x, torch.transpose(x, dim0 = 0, dim1 = 1)

(tensor([[0.8913, 0.1447, 0.5315],
         [0.1587, 0.6542, 0.3278]]),
 tensor([[0.8913, 0.1587],
         [0.1447, 0.6542],
         [0.5315, 0.3278]]))

In [86]:
x = torch.rand((2,2))
torch.det(x)

tensor(-0.0150)

In [87]:
torch.inverse(x)

tensor([[-46.9753,   7.2763],
        [ 10.9431,  -0.2716]])

In [88]:
# we can also perform relational operations like in numpy

In [94]:
torch.log(x), torch.exp(x), torch.sqrt(x), torch.sigmoid(x), torch.softmax(x, dim = 1)

(tensor([[-5.5061, -2.2181],
         [-1.8100, -0.3531]]),
 tensor([[1.0041, 1.1150],
         [1.1778, 2.0188]]),
 tensor([[0.0637, 0.3299],
         [0.4045, 0.8382]]),
 tensor([[0.5010, 0.5272],
         [0.5408, 0.6687]]),
 tensor([[0.4738, 0.5262],
         [0.3685, 0.6315]]))

In [97]:
x = torch.rand((2,2))
y = torch.rand((2,2))
x.add_(y) # inplace functions
# we can use any tensor.func_ to get the inplace function

tensor([[1.3917, 0.4840],
        [1.0457, 1.4923]])

In [100]:
# we can use assignment operator to copy a function 
# but this will create two references 
# so we use the a.clone() to copy the tensors

x.reshape(4,1)

tensor([[1.3917],
        [0.4840],
        [1.0457],
        [1.4923]])

In [101]:
x.flatten()

tensor([1.3917, 0.4840, 1.0457, 1.4923])

In [103]:
b = torch.rand(2,3,4)
b.permute(2,0,1)

tensor([[[0.2846, 0.4654, 0.3289],
         [0.9302, 0.3624, 0.6431]],

        [[0.2007, 0.1612, 0.1054],
         [0.6558, 0.3083, 0.3908]],

        [[0.5014, 0.1568, 0.9192],
         [0.0766, 0.0850, 0.6947]],

        [[0.3139, 0.2083, 0.4008],
         [0.8460, 0.0029, 0.0897]]])

In [106]:
b.unsqueeze(0).shape

torch.Size([1, 2, 3, 4])

In [110]:
x = torch.rand(1,20)
x.squeeze().shape

torch.Size([20])

In [112]:
b = x.numpy()
b

array([[0.92106473, 0.6947775 , 0.4751312 , 0.19854712, 0.19409746,
        0.05211657, 0.3370188 , 0.6688521 , 0.8188108 , 0.73084867,
        0.05802798, 0.19931877, 0.42109168, 0.98367476, 0.57232875,
        0.37051463, 0.7068576 , 0.30955923, 0.17637217, 0.8649436 ]],
      dtype=float32)

In [114]:
x = torch.from_numpy(b)
x

tensor([[0.9211, 0.6948, 0.4751, 0.1985, 0.1941, 0.0521, 0.3370, 0.6689, 0.8188,
         0.7308, 0.0580, 0.1993, 0.4211, 0.9837, 0.5723, 0.3705, 0.7069, 0.3096,
         0.1764, 0.8649]])