In [165]:
import pandas as pd
import numpy as np

In [166]:
from sklearn.datasets import make_classification

x,y = make_classification(n_samples = 100, n_features = 2, n_informative=1, n_redundant=1, n_classes=2,n_clusters_per_class=1, random_state=42,class_sep=10, hypercube=False)

In [167]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [168]:
x_train

array([[-2.25694799, -2.12957525],
       [-2.58352056, -2.43771742],
       [ 6.73148836,  6.3515912 ],
       [ 6.71274096,  6.33390182],
       [-3.80240494, -3.58781304],
       [-2.37847814, -2.24424674],
       [ 7.17443407,  6.7695389 ],
       [-2.65283553, -2.50312055],
       [ 6.95398896,  6.56153479],
       [-2.6121246 , -2.46470717],
       [ 6.83563691,  6.44986204],
       [-3.36036242, -3.17071756],
       [ 6.03940836,  5.69856931],
       [-2.7438555 , -2.58900373],
       [ 6.90054854,  6.51111032],
       [ 6.82240571,  6.43737755],
       [-3.15133789, -2.97348951],
       [-2.9601169 , -2.79306023],
       [ 7.00446271,  6.60916001],
       [-2.35572485, -2.22277755],
       [-3.6103781 , -3.40662339],
       [ 7.01567372,  6.61973832],
       [ 7.06789608,  6.66901346],
       [-2.35691449, -2.22390005],
       [-2.97746953, -2.80943355],
       [-3.09916442, -2.92426049],
       [ 7.20414907,  6.79757691],
       [-2.33130346, -2.1997344 ],
       [-2.43505325,

In [169]:
np.random.shuffle(x_train)
x_train

array([[-3.28841335, -3.102829  ],
       [ 6.58500836,  6.21337792],
       [-2.97361299, -2.80579466],
       [-3.6103781 , -3.40662339],
       [ 6.87828674,  6.49010489],
       [ 7.03803054,  6.64083342],
       [ 7.1049283 ,  6.70395574],
       [-2.83477656, -2.67479358],
       [ 7.01567372,  6.61973832],
       [-2.68702776, -2.5353831 ],
       [-2.99720168, -2.8280521 ],
       [ 6.83563691,  6.44986204],
       [-3.38448847, -3.19348203],
       [ 7.04352673,  6.64601942],
       [-2.43505325, -2.29762898],
       [-2.33130346, -2.1997344 ],
       [ 6.71274096,  6.33390182],
       [-2.95484983, -2.78809042],
       [-3.25529731, -3.07158189],
       [-3.20065808, -3.02002627],
       [ 7.0710994 ,  6.672036  ],
       [ 7.07559566,  6.67627852],
       [-2.97746953, -2.80943355],
       [ 7.0670446 ,  6.66821004],
       [ 6.03940836,  5.69856931],
       [-3.15133789, -2.97348951],
       [ 6.5513052 ,  6.18157682],
       [ 7.51073891,  7.08686409],
       [-2.25694799,

In [ ]:
class Perceptron:
    def __init__(self, learning_rate = 0.01, epochs = 1000):
        self.lr = learning_rate
        self.epochs = epochs
        self.weights = None

    def func(self, x):
        return 1 if x > 0 else 0

    def fit(self, x, y):
        x_ = np.insert(x, 0, 1, axis = 1)
        self.weights = np.ones(x_.shape[1])
        for i in range(self.epochs):
            indices = np.random.permutation(x_.shape[0])
            for k in indices:
                xi = x_[k]
                yi = y[k]

                y_pred = self.func(np.dot(xi, self.weights))
                y_diff = yi - y_pred
                xi_ = y_diff * xi
                self.weights = self.weights + self.lr * xi_

        return self

    def predict(self, x):
        x_ = np.insert(x, 0, 1, axis = 1)
        y_pred = np.dot(x_, self.weights) > 0
        return y_pred
         


In [171]:
model = Perceptron(learning_rate=0.01, epochs = 1000)
model.fit(x_train, y_train)

array([-0.04      , -0.0961112 , -0.03425125])

In [172]:
pred = model.predict(x_test)

In [173]:
x_test.shape

(20, 2)

In [174]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, pred)

0.0